"""add_entreprise_documents_candidatures_offer_skills

Revision ID: 33488d2660be
Revises: 
Create Date: 2026-07-02 20:01:59.849005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33488d2660be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laureats', sa.Column('cv_file_path', sa.String(length=500), nullable=True))
    op.add_column('offres', sa.Column('entreprise_id', sa.Integer(), nullable=True))
    op.add_column('offres', sa.Column('niveau_formation_requis', sa.String(length=100), nullable=True))
    op.add_column('offres', sa.Column('filiere_requise', sa.String(length=200), nullable=True))
    op.create_foreign_key(None, 'offres', 'entreprises', ['entreprise_id'], ['id'])
    op.add_column('users', sa.Column('entreprise_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'entreprises', ['entreprise_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'entreprise_id')
    op.drop_constraint(None, 'offres', type_='foreignkey')
    op.drop_column('offres', 'filiere_requise')
    op.drop_column('offres', 'niveau_formation_requis')
    op.drop_column('offres', 'entreprise_id')
    op.drop_column('laureats', 'cv_file_path')
    # ### end Alembic commands ###
